# Generated by Django 2.0.2 on 2018-06-01 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.CharField(blank=True, max_length=250)),
                ('address_line_2', models.CharField(blank=True, max_length=250)),
                ('city', models.CharField(blank=True, max_length=250)),
                ('state', models.CharField(blank=True, max_length=250)),
                ('postal_code', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.CharField(blank=True, max_length=250)),
                ('address_line_2', models.CharField(blank=True, max_length=250)),
                ('city', models.CharField(blank=True, max_length=250)),
                ('state', models.CharField(blank=True, max_length=250)),
                ('postal_code', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='cell_number',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='profile',
            name='billing_address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.BillingAddress'),
        ),
        migrations.AddField(
            model_name='profile',
            name='shipping_address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.ShippingAddress'),
        ),
    ]
