# Generated by Django 2.0.2 on 2018-06-04 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20180601_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='username',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='username',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
