# Generated by Django 2.0.2 on 2018-06-21 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='request',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
