# Generated by Django 2.0.2 on 2018-06-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_requests', '0005_auto_20180621_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='purchase_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
