# Generated by Django 2.0.2 on 2018-06-22 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_requests', '0007_auto_20180621_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='notes',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='purchase_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='reference_ID',
            field=models.CharField(blank=True, default='xxx', max_length=250),
        ),
        migrations.AlterField(
            model_name='request',
            name='url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
