# Generated by Django 2.0.2 on 2018-06-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_requests', '0010_request_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='downpayment_paid',
            field=models.BooleanField(default=False),
        ),
    ]
