# Generated by Django 2.0.2 on 2018-07-10 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_requests', '0011_request_downpayment_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='reference_ID',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
