# Generated by Django 2.0.2 on 2018-07-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_requests', '0012_auto_20180710_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='downpayment_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
