# Generated by Django 2.0.2 on 2018-07-11 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_requests', '0013_request_downpayment_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='downpayment_amount',
        ),
    ]
